version: 2
project_name: metacontroller
env:
  - REPOSITORY_OWNER={{ if index .Env "REPOSITORY_OWNER" }}{{ .Env.REPOSITORY_OWNER }}{{ else }}local{{ end }}
  - GC_FLAGS={{ if index .Env "DEBUG" }}all=-N -l{{ else }}-c 1{{ end }}
  - REMOVE_DEBUG_SYMBOLS={{ if index .Env "DEBUG" }}{{ else }}-s -w{{ end }}
#before:
#  hooks:
#    - make generated_files
builds:
  - env:
      - CGO_ENABLED=0
    main: ./pkg/cmd/metacontroller
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

    ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser {{ .Env.REMOVE_DEBUG_SYMBOLS }}
    gcflags:
      - "{{ .Env.GC_FLAGS }}"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
dockers_v2:
  - id: metacontroller
    images:
      - "{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}"
      - "ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}"
    dockerfile: Dockerfile
    tags:
      - latest
      - v{{ .Version }}
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    labels: &labels
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: "Lightweight Kubernetes controllers as a service"
      org.opencontainers.image.url: "https://github.com/metacontroller/metacontroller"
      org.opencontainers.image.source: "https://github.com/metacontroller/metacontroller"
      org.opencontainers.image.version: "v{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: "Apache-2.0"

  - id: metacontroller-distroless
    images:
      - "{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}"
      - "ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}"
    dockerfile: Dockerfile.distroless
    tags:
      - latest-distroless
      - v{{ .Version }}-distroless
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    labels: *labels

  - id: metacontroller-distroless-debug
    images:
      - "{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}"
      - "ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}"
    dockerfile: Dockerfile.distroless-debug
    tags:
      - latest-distroless-debug
      - v{{ .Version }}-distroless-debug
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    labels: *labels

  - id: metacontroller-debug
    images:
      - "{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}"
      - "ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}"
    dockerfile: Dockerfile.debug
    tags:
      - latest-debug
      - v{{ .Version }}-debug
    platforms:
      - linux/amd64
      - linux/arm64
    labels: *labels

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
release:
  mode: append
  footer: |
    ## Docker Images
    ### Github container registry
    - `ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:v{{ .Version }}`
    - `ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:latest`
    - `ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:v{{ .Version }}-distroless`
    - `ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:latest-distroless`
    - `ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:v{{ .Version }}-distroless-debug`
    - `ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:latest-distroless-debug`
    ### Dockerhub (will be deprecated !!)
    - `{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}:v{{ .Version }}`
    - `{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}:latest`
    - `{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}:v{{ .Version }}-distroless`
    - `{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}:latest-distroless`
    - `{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}:v{{ .Version }}-distroless-debug`
    - `{{ .Env.REPOSITORY_OWNER }}io/{{ .ProjectName }}:latest-distroless-debug`
    ## Helm chart
    ### Github container registry
    - `ghcr.io/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}-helm:{{ .Version }}`

  extra_files:
    - glob: manifests/production/*
